---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster-issuer
spec:
  acme:
    email: marco.w.liew@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-cluster-issuer
    solvers:
      # - dns01:
      #     route53:
      #       region: ap-southeast-2
      #       hostedZoneID: ${ZONE_ID}   
      #   selector:
      #     dnsZones:
      #       - xeniumsolution.online # You MUST update this 
      - http01:
          ingress:
            class: istio
        # selector:
        #   dnsZones:
        #     - xeniumsolution.online # You MUST update this 
